import os
import requests

async def send_audit_email(
    recipient_email: str,
    target_url: str,
    report_filepath: str,
    markdown_content: str,
):
    """Sends the generated audit report via direct Resend HTTP API to bypass container network routing blocks."""
    api_key = os.environ.get("RESEND_API_KEY", "")
    if not api_key:
        print("[Email Warning] RESEND_API_KEY environment variable is not set. Skipping email dispatch.")
        return

    try:
        sender_email = os.environ.get("RESEND_FROM_EMAIL", "audit@trilloka.com")

        # Read markdown content for the email body summary
        preview_snippet = (
            markdown_content[:1500] + "..."
            if len(markdown_content) > 1500
            else markdown_content
        )

        payload = {
            "from": sender_email,
            "to": [recipient_email],
            "subject": f"Your Trilloka Revenue Leak Audit Report: {target_url}",
            "html": (
                f"<h3>Revenue Audit Complete for {target_url}</h3>"
                "<p>Your comprehensive solution blueprint and gap analysis report "
                "has been successfully compiled.</p>"
                "<hr>"
                f"<pre style='white-space: pre-wrap; font-family: sans-serif;'>{preview_snippet}</pre>"
                "<hr>"
                "<p><i>Generated by Trilloka Revenue Readiness Engine.</i></p>"
            ),
        }

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }

        # Direct HTTP POST with explicit timeout to prevent hanging or IPv6 routing lockups
        response = requests.post(
            "https://api.resend.com/emails",
            json=payload,
            headers=headers,
            timeout=15
        )

        if response.status_code in [200, 201]:
            print(f"[Email Success] Report successfully sent to {recipient_email}")
        else:
            print(f"[Email Error] Resend API responded with status {response.status_code}: {response.text}")

    except Exception as e:
        print(
            f"[Email Error] Failed to dispatch audit email to {recipient_email}: "
            f"{str(e)}"
        )