import os
import socket
import resend

# Force IPv4 socket resolution to bypass [Errno 101] Network is unreachable 
# errors caused by cloud container IPv6 routing restrictions on Railway.
try:
    old_getaddrinfo = socket.getaddrinfo
    def new_getaddrinfo(*args, **kwargs):
        responses = old_getaddrinfo(*args, **kwargs)
        return [r for r in responses if r[0] == socket.AF_INET]
    socket.getaddrinfo = new_getaddrinfo
except Exception:
    pass

resend.api_key = os.environ.get("RESEND_API_KEY", "")


async def send_audit_email(
    recipient_email: str,
    target_url: str,
    report_filepath: str,
    markdown_content: str,
):
    """Sends the generated audit report via Resend API."""
    if not resend.api_key:
        print(
            "[Email Warning] RESEND_API_KEY environment variable is not set. "
            "Skipping email dispatch."
        )
        return

    try:
        # Use verified Resend domain sender address
        sender_email = os.environ.get("RESEND_FROM_EMAIL", "audit@trilloka.com")

        # Read markdown content for the email body summary
        preview_snippet = (
            markdown_content[:1500] + "..."
            if len(markdown_content) > 1500
            else markdown_content
        )

        params = {
            "from": sender_email,
            "to": [recipient_email],
            "subject": f"Your Trilloka Revenue Leak Audit Report: {target_url}",
            "html": (
                f"<h3>Revenue Audit Complete for {target_url}</h3>"
                "<p>Your comprehensive solution blueprint and gap analysis report "
                "has been successfully compiled.</p>"
                "<hr>"
                f"<pre style='white-space: pre-wrap; font-family: sans-serif;'>{preview_snippet}</pre>"
                "<hr>"
                "<p><i>Generated by Trilloka Revenue Readiness Engine.</i></p>"
            ),
        }

        response = resend.Emails.send(params)
        print(f"[Email Success] Report successfully sent to {recipient_email}")

    except Exception as e:
        print(
            f"[Email Error] Failed to dispatch audit email to {recipient_email}: "
            f"{str(e)}"
        )